### ISSUE TITLE
Unable to resolve "./types" 

### ISSUE THREAD

**Issue by boivado2** [stanleyugwu/react-native-bottom-sheet#1]
![2023-10-13](https://github.com/stanleyugwu/react-native-bottom-sheet/assets/63546434/bf0e556d-b41a-4501-b3b7-beb531d16bf7)

**Comment by stanleyugwu** [comment]
Hello @boivado2 , thanks for opening this issue.

Can you please provide more context to this issue? What are you trying to do exactly? 
Did you try to use the package or build it?

**Comment by stanleyugwu** [comment]
Hello again @boivado2 this issue has been resolved by PR #2 and a new version has been released [0.1.2](https://github.com/stanleyugwu/react-native-bottom-sheet/releases/tag/v0.1.2)

Thanks again for pointing this issue.

**Comment by boivado2** [comment]
Thanks @stanleyugwu, pardon me for not giving a detailed explanation about the error. I was trying to use the package.
