### ISSUE TITLE
Version 0.2.1 not available on NPM

### ISSUE THREAD

**Issue by Bartosz-L** [stanleyugwu/react-native-bottom-sheet#13]
As the title says, version 0.2.1 of the package is not available via npm

P.S Also wanted to thank you for a nice piece of code! Very useful and straightforward. 

![Zrzut ekranu 2024-01-17 o 15 42 33](https://github.com/stanleyugwu/react-native-bottom-sheet/assets/20401418/ce1e0171-07bd-4328-993c-a056e0229e3b)

**Comment by stanleyugwu** [comment]
😳 what the h...!! 😆 I think something went wrong when I was releasing.

Thanks a lot for pointing this out! I'll see to this ASAP!

**Comment by stanleyugwu** [comment]
Hey @Bartosz-L I just published version **0.2.1** to npm now. Thanks again!
