### ISSUE TITLE
Can not drag/swipe down after adding children

### ISSUE THREAD

**Issue by yashtops** [stanleyugwu/react-native-bottom-sheet#16]
Hello
Not able to slide/drag down bottom sheet from the children area.
if there is no children added it can be slide down from anywhere

```
<BottomSheet
          style={{ borderTopRightRadius: 16, borderTopLeftRadius: 16, backgroundColor: '#344104' }}
          height={WindowHeight -116}
          customDragHandleComponent={<View style={{ width: WindowWidth }} />}
          dragHandleStyle={{ backgroundColor: 'transparent' }}
          ref={sheetRef}>
<LinearGradient start={{ x: 0, y: 0 }} end={{ x: 0, y: 0.8 }} colors={['#677235', '#344104']}>
<BottomSheet
   style={{ borderTopRightRadius: 16, borderTopLeftRadius: 16, backgroundColor: '#344104' }}
   height={400}
   customDragHandleComponent={<View style={{ width: 100%' }} />}
   dragHandleStyle={{ backgroundColor: 'transparent' }}
   ref={sheetRef}>
             <Text style={{ color: 'white',fontSize: 20, padding: 20 }}>TEST</Text>
             <Text style={{ color: 'white',fontSize: 20, padding: 20 }}>TEST</Text>
</BottomSheet>
</LinearGradient>
</BottomSheet>
```

https://github.com/stanleyugwu/react-native-bottom-sheet/assets/120085933/3dffce74-bc5d-46e3-8af1-84eb1f7460f5

Actual behaviour :

Bottom sheet can not be access if there are children.

Expected behaviour :

It should be access it from anywhere.

![Screenshot 2024-02-14 at 12 26 35 PM](https://github.com/stanleyugwu/react-native-bottom-sheet/assets/120085933/afbb1a73-d8b0-4e8d-b910-0d6ababf48b2)

**Comment by stanleyugwu** [comment]
I'll take a look at this soon, thanks for reporting it

**Comment by yashtops** [comment]
Hello @stanleyugwu 
Thanks for the prompt response.
I am sorry i made a mistake to put the code snippet.actually i have a bottom sheet and it has LinearGradient as a main container and in future it might be `FlatList` inside and i don't want to use or show the handle or handler view area that's why i have set it empty `<View/>`.so still i am not able to slide it down or can not use gesture to shut it down.let me know if it make sense or fixable.

```
const Handle = () => {
        return (
            <View style={{ width: WindowWidth }} />
        )
 }
<BottomSheet
          style={{ borderTopRightRadius: 16, borderTopLeftRadius: 16, backgroundColor: '#344104' }}
          height={WindowHeight -116}
          customDragHandleComponent={Handle}
          dragHandleStyle={{ backgroundColor: 'transparent' }}
          ref={sheetRef}>
<LinearGradient start={{ x: 0, y: 0 }} end={{ x: 0, y: 0.8 }} colors={['#677235', '#344104']}>
             <Text style={{ color: 'white',fontSize: 20, padding: 20 }}>TEST</Text>
             <Text style={{ color: 'white',fontSize: 20, padding: 20 }}>TEST</Text>
</LinearGradient>
</BottomSheet>
```

Thanks

**Comment by stanleyugwu** [comment]
Hi again @yashtops, incase you're still looking for a workaround for this, here's the line of code that causes the current behavior.

https://github.com/stanleyugwu/react-native-bottom-sheet/blob/b4b3455d230e70b06bb03fff8defea3e5ffdd15a/src/components/bottomSheet/index.tsx#L252

If you set `return` to `true` instead, i.e. `return true` then you'll have the behavior you want.

That will be a workaround for now, I'm working to have a major fix or implementation for the correct behavior

**Comment by stanleyugwu** [comment]
I also just pushed a patch for it in [patch-1](https://github.com/stanleyugwu/react-native-bottom-sheet/tree/patch-1) branch.

In the meantime you can install the package from that branch using `npm install stanleyugwu/react-native-bottom-sheet#patch-1` while I work towards a permanent fix.
