### ISSUE TITLE
Prevent closing

### ISSUE THREAD

**Issue by pranavbabu** [stanleyugwu/react-native-bottom-sheet#19]
Hey, first of all, this is great library and good job! I wonder if it's possible to prevent bottom sheet from closing, lets say to show some warning for user in some cases.

**Comment by stanleyugwu** [comment]
Hey @pranavbabu I'm glad this package is useful to you.

And yes! you can disable closing by just setting `closeOnDragDown ` prop to `false`

E.g
```tsx
<BottomSheet ref={sheetRef} closeOnDragDown={false}>
...
</BottomSheet/>
```

**Comment by stanleyugwu** [comment]
There's **onClose** callback
