### ISSUE TITLE
Auto Height Problem

### ISSUE THREAD

**Issue by ynssenem** [stanleyugwu/react-native-bottom-sheet#20]
I didn't understand how they set the auto height in the third item of the Readme.md. Can you share a code example? Also, good documentation is needed.

![image](https://camo.githubusercontent.com/24387b3403b7c4bd7558d4855fda6d2b660d8e4e4f180c1ff6f5627613b22a22/68747470733a2f2f692e6962622e636f2f335947584868742f4465746563742d4865696768742e676966)

**Comment by stanleyugwu** [comment]
Okay for the moment, the bottom sheet doesn't automatically adjust it's height.

To do that imperatively, you have to extract height prop into a state and pass the state to the sheet. When that state changes, the sheet will adjust its height accordingly.

E.g below code will auto-adjust the height of the sheet when you click on the "Adjust" button inside the sheet. I plan to add auto height adjustment later, but for now this is how to achieve that.

```tsx
export default function App() {
  const sheetRef = React.useRef<BottomSheetMethods>(null);
  const [dynamicHeight, setDynamicHeight] = React.useState(200)

  return (
    <View>
      <Button title="Open Sheet"  onPress={() => sheetRef.current?.open()} />
      <BottomSheet ref={sheetRef} height={dynamicHeight}>
        <Button title='Adjust Height' onPress={() => setDynamicHeight(400)} />
      </BottomSheet>
    </View>
  );
}
```

**Comment by anup-a** [comment]
Hi @stanleyugwu So, currently the lib does not support automatic height ? Any workaround we could use meanwhile

**Comment by stanleyugwu** [comment]
Yes. I have plans to add more features as soon as I can squeeze out time. For the meantime you can try the workaround above
