### ISSUE TITLE
How to make the height of the BottomSheet to fit its content?

### ISSUE THREAD

**Issue by alienzhangyw** [stanleyugwu/react-native-bottom-sheet#32]
Cannot set the height to "auto" right now.

Or, in other words, how can I fill the BottomSheet space with a {flex: 1} View?

**Comment by stanleyugwu** [comment]
You have to set the height because the bottom sheet supports scrolling. But you can set height in pixels `height={400}` or percentage `height={'80%'}` if that helps

**Comment by stanleyugwu** [comment]
Try `height:'100%'`

**Comment by stanleyugwu** [comment]
Lemme know if it works

**Comment by alienzhangyw** [comment]
What I need is a button fixed to the bottom of the BottomSheet, while some changeable contents are above the button (no scroll), and the BottomSheet's height is just enough, no space left. Maybe like `@gorhom/bottom-sheet`'s [dynamic sizing feature](https://gorhom.dev/react-native-bottom-sheet/dynamic-sizing).

**Comment by stanleyugwu** [comment]
Well at the moment, dynamic sizing isn't supported out of the box. You have to set the height of the sheet explicitly, and if you don't it takes a default height.

**Comment by stanleyugwu** [comment]
I'm still yet to figure out the best approach to implementing dynamic sizing without having to add pre configured components like with `@gorhom/bottom-sheet`

**Comment by stanleyugwu** [comment]
For now, either you measure your content and set the sheet's height accordingly, or you make just the changeable content scrollable if you're not sure it's height.

**Comment by alienzhangyw** [comment]
> For now, either you measure your content and set the sheet's height accordingly, or you make just the changeable content scrollable if you're not sure it's height.

Ok then

**Comment by alienzhangyw** [comment]
> > > Try `height:'100%'`
> > 
> > 
> > Not working, it seems the content's height become the screen's full height.
> 
> That's strange, I tried it on a view and it worked fine.
> 
> ```tsx
> <BottomSheet ...>
>     <View style={{height:'100%'}}>
>       // children
>     </View>
> </BottomSheet>
> ```

```
<BottomSheet ...>
    <View style={{height:'100%'}}>
      <View>Some content</View>
      <View style={{ flex: 1 }} />
      <Button>Confirm</Button>
    </View>
</BottomSheet>
```

The button went out of the screen.

Maybe it's because of this View?
https://github.com/stanleyugwu/react-native-bottom-sheet/blob/a98e1b13db39b4ffc6db390596a0fdc24bc2bdea/src/components/bottomSheet/index.tsx#L503C1-L508C20

It doesn't have a style of `flex: 1` or `height: '100%'`.

**Comment by stanleyugwu** [comment]
Could you add the height or flex to the `View` locally just to see if it works

**Comment by stanleyugwu** [comment]
Also, is this necessary? Wonder what it does.

`<View style={{ flex: 1 }} />`

**Comment by alienzhangyw** [comment]
> Could you add the height or flex to the `View` locally just to see if it works

`flex: 1` works:
```tsx
            <View
              // we apply padding styles here to not affect drag handle above
              style={[sepStyles?.paddingStyles, { flex: 1 }]}
            >
              {ChildNodes}
            </View>
```

> Also, is this necessary? Wonder what it does.

This is just an example to fill the space and keep the Button to the bottom.
