### ISSUE TITLE
provide a way to control how it behavior on keyboard

### ISSUE THREAD

**Issue by segun-flexible** [stanleyugwu/react-native-bottom-sheet#6]
i set some input inside the bottom sheet, so when the input is focused, the bottom sheet will dragged down just as you can see in the below video, provide a way to handle or disable such behavior. or let the system handle that itself

https://github.com/stanleyugwu/react-native-bottom-sheet/assets/52238200/eefd9ba1-bdbb-4b5f-a122-9fe93104d64a

**Comment by stanleyugwu** [comment]
Sorry for that.

That behavior I'd say is the tradeoff for handling all keyboard behaviors and soft input modes `adjustResize` and `adjustPan` automatically without having you use custom text input or wrap contexts or use custom hooks.

For example if you let the system handle that, then in your case the sheet and text input will go way over the screen when keyboard's out (for `adjustResize` input mode).

But then I think adding the ability to disable this smart handling will make sense, so users can have the default behavior.

I'll definitely look into adding that and bumping to 2.1.0 ASAP!

Thanks a bunch ✌🏽

**Comment by segun-flexible** [comment]
Don't worry, implement what you wanna implement, I will wait
