### ISSUE TITLE
it doesnt open 

### ISSUE THREAD

**Issue by Ahsanali012** [stanleyugwu/react-native-bottom-sheet#7]
The bottom sheet doesnt show on the button Onpress on android

**Comment by stanleyugwu** [comment]
Hey @Ahsanali012 can you show me what your code looks like?

**Comment by Ahsanali012** [comment]
It's the same code which is given in example of documentation. On button press it's not showing any bottomsheet

**Comment by stanleyugwu** [comment]
That's strange, I am currently using the latest version of the package in one of my projects and it works fine.

Just to have more pair of eyes on it, can you please paste me your code here?
